### ISSUE TITLE
problem: search bar result isn't clear enough

### ISSUE THREAD

**Issue by cathfung** [EmurgoHK/cardanoupdate#444]
If there are a lot of contents (eg:100 essays) related to searched keywords then the user can't tell if these are already filtered or not from the screen, there's nothing like "10 results were found" or no highlighted searched words in the content 

<img width="1057" alt="screen shot 2018-11-05 at 1 20 55 pm" src="https://user-images.githubusercontent.com/44600923/47979456-3fb5e380-e0fe-11e8-92e9-eb46da752b20.png">

**Comment by AshHimself** [comment]
Maybe we can remove search on each page and concentrate on a single search solution? @gazhayes 

Possibly add in highlighting, more complex search operators etc.

**Comment by gazhayes** [comment]
Yeah I was thinking the same thing.

**Comment by porcellus** [comment]
I don't think we should remove the search bar from each page, what I would prefer is either the current solution with a common component doing the actual search or we could redirect to the global search page with proper filters set.
In my opinion, the best solution is to have an advanced search link under the search bars, linking to the global search page while having the content below it either be a search result component or a simple list. We could even reuse the search component with only the content type filter set as the list instead of having separate components for that.

**Comment by gazhayes** [comment]
@porcellus I'm totally happy with that if you want to do that

**Comment by geekyd** [comment]
@porcellus That sounds great.

**Comment by porcellus** [comment]
I'll do that tomorrow (hopefully) then
@emurgobot claim

**Comment by porcellus** [comment]
I'll do moving to a common search result component in different issue as that isn't a minimal solution to this (and the current search page looks too different from what we have on other pages)
@emurgobot done in #492
