### ISSUE TITLE
problem: cannot change vote after voting

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#54]
problem: users cannot change their vote after voting on a news item.

**Comment by samuelralak** [comment]
The voting system is quite confusing as well. We are using a vote up/down
system yet displaying stars. IMO we should only display number votes
up(thumb ups) vote downs (thumb downs) instead of the star. or if you we
are to go with stars, lets use a star based voting system only.

Am for the thumb based voting (vote up/down)

**Comment by gazhayes** [comment]
@samuelralak how's this one going?

**Comment by samuelralak** [comment]
currently updating tests. sending PR in a bit

**Comment by samuelralak** [comment]
@emurgobot done

done in #115
