### ISSUE TITLE
problem: cards on home route are sorted too orderly

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/cardanoupdate#558]
problem: on small screens etc it's easy to think the site only has one (or minimal number) type of item (e.g. only projects) because everything is ordered by type.

solution: decouple the view logic from the collection logic (I think the bounties page of blockrazor does something like this) so that cards can be sorted in the UI without needing to change the mongo call. Find some way to sort the cards randomly in the UI.

**Comment by porcellus** [comment]
They should be ordered by creation date regardless of type. Last time I worked on it the sorting was already decoupled from collection logic and done on the client. I'll check again tonight. Most likely it's just that someone added different types in batches, so the correct order doesn't seem random enough. we can try to do something about that, but I'm not sure how to randomize the order.

**Comment by geekyd** [comment]
The logic is already decoupled, by default the items are sorted by date. However it may seem to be sorted too orderly if same type of resources are created in small timeframes. If we still need this I we can sort the items by title instead of date by default.

**Comment by porcellus** [comment]
A few things came to mind, but I can imagine scenarios going wrong. Some things we could try:
- only allowing x of the same type to follow each other (this can result in having only 2 types that switch)
- making sure 1 of each type is in top x: messes up ordering completely. 
- Adding a "newest x" section for each type and having the rest as "archive" ordered by date added.
As a side note, we could use the event start date as the basis for the ordering instead of the date of creation, although this may go wrong if there are many upcoming events added, burying the freshly added events.

**Comment by gazhayes** [comment]
Hmmm, ok, I'll close this for now and ask some users what they think.
